version: '3.8'

services:
  civicfix-mysql:
    image: mysql:8.0
    container_name: civicfix-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: civicfix_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
